### PR TITLE
bump version to 2.4.0-snapshot

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Comment by sazzad16** [comment]
Why not bump to a major version after a breaking change https://github.com/RedisGraph/JRedisGraph/commit/ed0c37c6708709ec0a27140897ac1a496b586010?

**Comment by sazzad16** [comment]
@gkorland 
> Why not bump to a major version after a breaking change ed0c37c?

**Comment by gkorland** [comment]
@sazzad16 the semantic versioning we are using X.Y.Z
Z - bugs
Y - Features
X - Major features and breaking changes

**Comment by sazzad16** [comment]
@gkorland https://github.com/RedisGraph/JRedisGraph/commit/ed0c37c6708709ec0a27140897ac1a496b586010 is a breaking change.
Shouldn't it fall under X?
> X - Major features and **breaking changes**

**Comment by gkorland** [comment]
I guess we should have try to push this change to a major relaese.

**Comment by sazzad16** [comment]
> I guess we should have try to push this change to a major relaese.

@gkorland :+1:

**Pull request merged**
